const DOCUMENT_STATUS_ARCHIVE = 11;
const DOCUMENT_STATUS_APPROVED = 4;
const DOCUMENT_STATUS_ON_WORK = 5;
const DOCUMENT_STATUS_REWORK = 7;
const DOCUMENT_STATUS_DELETE = 13;

const DOCUMENT_TASK_STATUS_ASSIGNED = 1;
const DOCUMENT_TASK_STATUS_COMPLETE = 2;

module.exports = {
  DOCUMENT_STATUS_ARCHIVE,
  DOCUMENT_STATUS_APPROVED,
  DOCUMENT_TASK_STATUS_ASSIGNED,
  DOCUMENT_TASK_STATUS_COMPLETE,
  DOCUMENT_STATUS_ON_WORK,
  DOCUMENT_STATUS_REWORK,
  DOCUMENT_STATUS_DELETE,
};
